version: '2'
services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile.builder
    image: builder
    labels:
      lagoon.type: cli
    volumes:
      - ./web:/app/web:delegated
  nginx:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile.nginx
    labels:
      lagoon.type: nginx-php
      lagoon.name: nginx-php
    volumes:
      - ./web:/app/web:delegated
    depends_on:
      - cli
    expose:
      - "8080"
    environment:
      - AMAZEEIO_URL=drupal.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=8080
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    labels:
      lagoon.type: nginx-php
      lagoon.name: nginx-php
    volumes:
      - ./web:/app/web:delegated
    depends_on:
      - cli
  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    labels:
      lagoon.type: mariadb
networks:
  amazeeio-network:
    external: true
