version: '2'
services:
  cli:
    build:
      context: .
      dockerfile: Dockerfile.builder
    image: builder
    labels:
      lagoon.type: cli-persistent
      lagoon.persistent: /app/web/sites/default/files/
      lagoon.persistent.name: nginx
    volumes:
      - .:/app:delegated
    volumes_from:
      - container:amazeeio-ssh-agent
    environment:
      - SSH_AUTH_SOCK=/tmp/amazeeio_ssh-agent/socket
      - LAGOON_ROUTE=http://drupal-nginx.docker.amazee.io
  nginx:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: Dockerfile.nginx
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.persistent: /app/web/sites/default/files/
      lagoon.persistent.class: bulk
      lagoon.name: nginx
    volumes:
      - .:/app:delegated
    depends_on:
      - cli
    expose:
      - "8080"
    environment:
      - AMAZEEIO_URL=drupal-nginx.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=8080
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    labels:
      lagoon.type: nginx-php-persistent
      lagoon.persistent: /app/web/sites/default/files/
      lagoon.name: nginx
      lagoon.persistent.class: bulk
# # Uncomment the following lines to enable xdebug in php and then restart the php container
#     environment:
#        - XDEBUG_ENABLE=true
    volumes:
      - .:/app:delegated
    depends_on:
      - cli
  mariadb:
    image: amazeeio/centos7-mariadb10-drupal
    labels:
      lagoon.type: mariadb
  redis:
    image: amazeeio/redis
    labels:
      lagoon.type: redis
  varnish:
    image: amazeeio/varnish-drupal
    networks:
      - amazeeio-network
      - default
    labels:
      lagoon.type: varnish
    links:
      - nginx
    environment:
      - AMAZEEIO_URL=drupal.docker.amazee.io
      - AMAZEEIO=AMAZEEIO
      - AMAZEEIO_HTTP_PORT=8080

networks:
  amazeeio-network:
    external: true
